### ISSUE TITLE
Error while installing mie

### ISSUE THREAD

**Issue by PiyushX23** [scottprahl/mie#1]
Hi... 

I tried to install mie as per the given instruction but I am facing following error while doing make.
I think it is related to "_ctangel_"
Please help me to resolve this.

_cd src; make
make[1]: Entering directory '/home/piyush/Downloads/mie/src'
./version.pl
/usr/bin/gcc -fno-common -O3    -c -o version.o version.c
ctangle mie_main.w - mie_main.c
make[1]: ctangle: Command not found
make[1]: *** [<builtin>: mie_main.c] Error 127
make[1]: Leaving directory '/home/piyush/Downloads/mie/src'
make: *** [Makefile:63: mie] Error 2_

**Comment by scottprahl** [comment]
Download the most recent version from github.

All the files should now be present and ctangle should not be needed.

If you are still having problems you can wait for me to fix things or build ctangle yourself

   git clone https://github.com/ascherer/cweb.git

**Comment by PiyushX23** [comment]
Can I use  "git clone https://github.com/ascherer/cweb.git" to build ctangle?
But it is written that his project is incomplete and give the compiler warnings.
Should I still use this to build "ctangle"?

**Comment by scottprahl** [comment]
OK.  Try now.  I just uploaded the files and added a new release.  Should work now.

**Comment by scottprahl** [comment]
I am going to close this issue since I think it has been addressed.  If not then please start a new issue.
