### ISSUE TITLE
installation still gives ctangle issue

### ISSUE THREAD

**Issue by PiyushX23** [scottprahl/mie#2]
Hi...

sorry I was out for last week, but I am still facing the same issue regarding ctangle, while installing mie. Following is an error, I am facing.

`ctangle -bph test_mie
make[1]: ctangle: Command not found
`

Additionally, can you help me to suggest, how one can calculate backscattering efficiency using Wiscombe code? because I think Wiscombe Fortran code does not directly provide backscattering efficiency.

Thank you

**Comment by scottprahl** [comment]
yep, you're right.  I missed those.  I just uploaded those to github.  Please do a `git pull` and try to rebuild.

**Comment by PiyushX23** [comment]
Hi...
thank you for your supports.
The issue got resolved and I installed it successfully. 
can you suggest me, how one can calculate backscattering efficiency using Wiscombe code? because I think Wiscombe Fortran code does not directly provide backscattering efficiency.

**Comment by scottprahl** [comment]
The backscattering efficiency is calculated for you.
```
void Mie(double x, struct c_complex m, double *mu, long nangles, struct c_complex *s1, 
           struct c_complex *s2, double *qext, double *qsca, double *qback, double *g)
```
The details of the calculation are on page 44 of the documentation in `doc/mie_doc.pdf` and follow that given in the usual texts Bohren & Huffman or van de Hulst

**Comment by PiyushX23** [comment]
Thank you, Scott, for your kind help.

I have a query regarding your python version of Mie code.

I was trying to compare the results from original BHMIE Fortran code and
miepython (a python version of your code).
I found that both provide similar results of extinction and scattering
efficiencies but backscatter efficiency is different.
MiePython (python version provides) 10 order of higher value of backscatter
than BHMIE code.

Here is my python script for MiePython

import miepython as mp
m=1.77-0.63j
radius=150nm
wavelength=375nm
x=2.512
qext,qsca,qback=mp.mie(m,x)

outcomes:
qext=2.858594660377669
qsca=1.314966237440868
QBACK=0.20212578330774

The input and outcome of BHMIE code is attached here as a text file

Best Regards
Piyushkumar Patel
----------------------------------------------------------------------------------------
*NASA Postdoctoral Fellow*
*Aerosols & Clouds (329J)*
*Jet Propulsion Laboratory, Mail Stop 183-715,*

*4800 Oak Grove Drive, Pasadena, California 91109, USA*

*Tel: +1-818-354-3234*
*alternate email: piyushkumar.n.patel@jpl.nasa.gov <piyushpatel@prl.res.in>*
----------------------------------------------------------------------------------------

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
21/10/19,
12:58:23 pm

**Comment by scottprahl** [comment]
Ack.  I replied by email instead of on issue tracker.  

The problem is the definition of backscattering efficiency.  The one that I use (Wiscombe's) which evidently differs from that of Bohren & Huffman by a factor of 4pi.

The is explained in 
  https://github.com/scottprahl/miepython/blob/master/doc/02_efficiencies.ipynb
